# Website details
name: "10th"
description: "10thçš„blogs"
email: "silencly520@163.com"
author: "10th"
lang: ""
locale: ""

# Jekyll
paginate: 10
highlighter: ""
markdown: kramdown
gems: [jekyll-paginate]
timezone: Europe/Istanbul
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: 
domain_name: 'https://quality520.github.io/'
google_analytics: 'UA-XXXXXXXX-X'

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Details for the RSS feed generator
# url:            '/rss.xml'
url:            'blog url'
author:         '10th'

# Search engine verifications
bing: ""
yandex: ""
google: ""

#Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"
    include_posts:
        - "/index.html"
    change_frequency_name: "daily"
    priority_name: "1.00"

